[2025-06-18 16:25:55,432] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.create_postgres_table 2025-05-03T00:00:00+00:00 [queued]>
[2025-06-18 16:25:55,478] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: connect_postgres_dag.create_postgres_table 2025-05-03T00:00:00+00:00 [queued]>
[2025-06-18 16:25:55,479] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:25:55,479] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2025-06-18 16:25:55,479] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:25:55,514] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2025-05-03T00:00:00+00:00
[2025-06-18 16:25:55,524] {standard_task_runner.py:52} INFO - Started process 3235 to run task
[2025-06-18 16:25:55,529] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'connect_postgres_dag', 'create_postgres_table', '2025-05-03T00:00:00+00:00', '--job-id', '16393', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connect_postgres_dag.py', '--cfg-path', '/tmp/tmppg2qdzdf', '--error-file', '/tmp/tmpb1cstsnm']
[2025-06-18 16:25:55,533] {standard_task_runner.py:77} INFO - Job 16393: Subtask create_postgres_table
[2025-06-18 16:25:55,649] {logging_mixin.py:104} INFO - Running <TaskInstance: connect_postgres_dag.create_postgres_table 2025-05-03T00:00:00+00:00 [running]> on host ee91c01336f6
[2025-06-18 16:25:55,758] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=connect_postgres_dag
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2025-05-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-05-03T00:00:00+00:00
[2025-06-18 16:25:55,759] {postgres.py:69} INFO - Executing: 
            create table if not exists employee (
                "name" text,
                "age" integer,
                "salary" numeric
            )
        
[2025-06-18 16:25:55,776] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: postgres, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2025-06-18 16:25:55,787] {dbapi.py:180} INFO - Running statement: 
            create table if not exists employee (
                "name" text,
                "age" integer,
                "salary" numeric
            )
        , parameters: None
[2025-06-18 16:25:55,790] {dbapi.py:186} INFO - Rows affected: -1
[2025-06-18 16:25:55,793] {postgres.py:73} INFO - NOTICE:  relation "employee" already exists, skipping

[2025-06-18 16:25:55,833] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=connect_postgres_dag, task_id=create_postgres_table, execution_date=20250503T000000, start_date=20250618T162555, end_date=20250618T162555
[2025-06-18 16:25:56,030] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18 16:25:56,065] {local_task_job.py:146} INFO - Task exited with return code 0
